name: browserslist-update-action
description: Runs `npx browserslist@latest --update-db` on a repository and proposes a pull request to merge updates.
author: Camptocamp Association
branding:
  icon: bar-chart-2
  color: green
inputs:
  github_token:
    description: GitHub secret
    required: true
  branch:
    description: The pull request branch name
    required: false
    default: browserslist-update
  base_branch:
    description: The target branch into which the pull request will be merged
  directory:
    description: For monorepos, directory to switch to
    required: false
    default: .
  commit_message:
    description: The message to use when committing changes
    required: false
    default: Update caniuse database
  title:
    description: The title of the pull request
    required: false
    default: 📈 Update caniuse database
  body:
    description: The body of the pull request
    required: false
    default: Caniuse database has been updated. Review changes, merge this PR and have a 🍺.
runs:
  using: 'node16'
  main: 'dist/index.js'
