/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Autogenerated input type of CreatePullRequest
 */
export interface CreatePullRequestInput {
  readonly repositoryId: string;
  readonly baseRefName: string;
  readonly headRefName: string;
  readonly title: string;
  readonly body?: string | null;
  readonly maintainerCanModify?: boolean | null;
  readonly draft?: boolean | null;
  readonly clientMutationId?: string | null;
}

/**
 * Autogenerated input type of DeleteRef
 */
export interface DeleteRefInput {
  readonly refId: string;
  readonly clientMutationId?: string | null;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
